spring:
  datasource:
    url: jdbc:mysql://localhost:3306/checkin_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: tientai24
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
server:
  port: 8080
app:
  checkin:
    points:
      day1: 1
      day2: 2
      day3: 3
      day4: 5
      day5: 8
      day6: 13
      day7: 21